### PR TITLE
adding Fruit Baskets

### PR DESCRIPTION
**Pull request by Entixs**

### CODE REVIEW

**Comment by p0psicles** [comment]
Why does it need Two years?

**Comment by p0psicles** [comment]
Diores it have release names like `fruit baskets (2020) s02e01`?

**Comment by Entixs** [comment]
I been trying to make it pull the correct season but it seems like there is an issue. I been trying to give it scene exceptions but it's not working. I thought this edit would work.

**Comment by p0psicles** [comment]
Just going from the logs you need those:
```
"357488": {
            "-1": [
                "Fruit Baskets (2019)"
            ],
            "2" [
                "Fruit Baskets S2 (2019)"
            ]
        }
```

**Comment by Entixs** [comment]
> Just going from the logs you need those:
> 
> ```
> "357488": {
>             "-1": [
>                 "Fruit Baskets (2019)"
>             ],
>             "2" [
>                 "Fruit Baskets S2 (2019)"
>             ]
>         }
> ```

Make sure it's Fruits Basket (2019) and Fruits Basket S2 (2019). How they named the anime is weird... I didn't realize until after looking at the logs.

**Pull request merged**
